### ISSUE TITLE
Rework core API

### ISSUE THREAD

**Issue by pkosiec** [pkosiec/mongo-seeding#102]
In near future, I would like to rewrite Mongo Seeding core. It may introduce some breaking changes, as I want to support additional features, without making the API too complex.

While rethinking API, I want to consider the following abilities:
- seed multiple databases with different users (#73) 
- use own MongoDB client
- minimize custom code as possible (for example, by migrating to built-in reconnect feature in Mongo client - #97)
- handle `.mjs` files (#105)

**Comment by gimyboya** [comment]
First of all thank you for this amazing tool.

I am currently missing mongoose support. any idea of when that gonna land?

**Comment by pkosiec** [comment]
Hi @gimyboya,
Thanks for very kind words 🙂 
Unfortunately I can't tell precisely when the Mongo Seeding will land. It's a huge change and I want to start with API redesign. However, currently I don't have that much time to implement such big changes. Hopefully I will be able to work on that next year, but can't promise that 😞

**Comment by yharaskrik** [comment]
Hey @pkosiec if there was some kind of spec of how you want the core to be designed maybe we could contribute to it, my company uses your library for all of our APIs e2e tests but would love a way to specify custom tsconfigs and support for more than just a single export. Would be happy to contribute if possible! Would make our lives quite a bit easier!

**Comment by pkosiec** [comment]
Hi @yharaskrik! Thank you, I really appreciate that.

Currently I don't have any specification nor time to design a new API 😞 I would like to rewrite Mongo Seeding, as I see a huge room for improvement when it comes to API and also code quality. But I'll be honest with you: I didn't use MongoDB from a long period of time. Also, TypeScript is not my primary language from a few years now. That's why the motivation for complete rewrite of Mongo Seeding is low - I think it's understandable if I don't use Mongo Seeding by myself.

But! It doesn't mean Mongo Seeding is going to be archived or unmaintained anytime soon - no, I still like to develop some features, as long as they don't consume much time for me.


Regarding contribution: sure, I'm open for any contribution 🙂 To ensure the ideas for new features are discussed and accepted, please always start from creating an issue before actual implementation.

I would like to hear more about your ideas for the features. Could you please elaborate bit about them?

>  would love a way to specify custom tsconfigs

Hmm, but that should be supported out of the box 🤔 `ts-node` loads the `tsconfig.json` automatically, similarly to `tsc`: https://github.com/TypeStrong/ts-node#loading-tsconfigjson

> support for more than just a single export

Do you mean the support for multiple exports (named exports) in TypeScript data import files? Or something else?

It would be great if you could open brand-new issues (one per feature idea) to make our discussion more visible for others. Thanks a lot!

**Comment by pkosiec** [comment]
Closing this issue for now as major API changes are not planned unless there's a specific feedback from the community 🙂
