### ISSUE TITLE
import(..) returns undefinded instead of results of resolution

### ISSUE THREAD

**Issue by gerwinbrunner** [pkosiec/mongo-seeding#106]
When the `import(..)` function is called the results are not returned, but a `undefined`
This leads to problems when using trying to use this package with cypress.

The for loop does not return the results of the promises
https://github.com/pkosiec/mongo-seeding/blob/master/core/src/importer/index.ts#L25-L28

If we would use a map and return instead of the `for` loop the issue could be solved.
What do you think?

**Comment by gerwinbrunner** [comment]
This is the actual error message:

**Comment by gerwinbrunner** [comment]
So after some investigation I found the issue to be that this function does not return anything - so it returns undefined.

https://github.com/pkosiec/mongo-seeding/blob/master/core/src/index.ts#L119

So if we add a `return true` all is good :)

**Comment by pkosiec** [comment]
Hi @gerwinbrunner, thank you for your contribution!

Yes, you're right - currently, the import function resolves with the `undefined` value. However, I don't see any problem with this approach. Could you please elaborate a bit about the issues you encounter with using `mongo-seeding` along with Cypress? 

Thanks!

**Comment by gerwinbrunner** [comment]
Sure!

in cypress I define a task to seed the data:

```
module.exports = (on) => {
  on("task", {
    "seed:database:baseAccountsEnabled": () => {
      const config = {
        database: "mongodb://localhost:3051/meteor",
        dropDatabase: true,
      };
      const mongoSeeder = new SeederClass(config);
      // console.log("seed:database:baseAccountsEnabled start");
      const p = path.resolve(folder);
      // console.log("seed:database:baseAccountsEnabled path", p);

      const collections = mongoSeeder.readCollectionsFromPath(p, {
        extensions: ["js", "json", "ts"],
        //transformers: [Seeder.Transformers.replaceDocumentIdWithUnderscoreId],
      });
      return mongoSeeder.import(collections);
    },
  });
};

```

Calling this task raises the error mentioned in a previous post. The data import is anyway done  successfully before the error is raised.

The return of the `undefined` raises the error - this is documented in the cypress task definition here:
https://docs.cypress.io/api/commands/task.html#Command

**Comment by gerwinbrunner** [comment]
Anyway I found a workaround for now:

```
module.exports = (on) => {
  on("task", {
    "seed:database:baseAccountsEnabled": async () => {
      const config = {
        database: "mongodb://localhost:3051/meteor",
        dropDatabase: true,
      };
      const mongoSeeder = new SeederClass(config);
      // console.log("seed:database:baseAccountsEnabled start");
      const p = path.resolve(folder);
      // console.log("seed:database:baseAccountsEnabled path", p);

      const collections = mongoSeeder.readCollectionsFromPath(p, {
        extensions: ["js", "json", "ts"],
        //transformers: [Seeder.Transformers.replaceDocumentIdWithUnderscoreId],
      });

      const prom = mongoSeeder.import(collections);
      await prom;
      return true;
    },
  });
};


```

**Comment by pkosiec** [comment]
@gerwinbrunner Yup, the workaround looks like it is the best approach here. I would only slightly modify the two lines there:

```javascript
await mongoSeeder.import(collections);
return true;
```

It seems right to me - because this is specific requirement from Cypress. And as I wrote before, resolving promise with `undefined` is just as fine as returning from function with `undefined`.

Do you feel convincedthat this is not the issue of Mongo Seeding? 😄 If so, can we close this issue and PR?

**Comment by gerwinbrunner** [comment]
Yeah, sure - the workaround is fine for me.

**Comment by pkosiec** [comment]
I wouldn't treat it as a workaround, but in this case as a proper solution 🙂 Anyway, thanks for the openness and good open source attitude 🙂 Cheers!
