### ISSUE TITLE
Mongo Connection Timeouts because of default DEFAULT_CLIENT_OPTIONS

### ISSUE THREAD

**Issue by lukasburns** [pkosiec/mongo-seeding#109]
Version: 3.4.0

Hi, Great Library! 
Im getting  a connection timeout error. Inspecting a little more I found out that it is because
the current DEFAULT_CLIENT_OPTIONS for the DatabaseConnector are as follow:
```
DatabaseConnector.DEFAULT_CLIENT_OPTIONS = {
    ignoreUndefined: true,
    useNewUrlParser: true,
    useUnifiedTopology: true,
    connectTimeoutMS: 1,
};
```

where the connectTimeoutMS is 1 milli second, therefor getting a timeout every time.

I've tried setting the mongoClientOptions in the Seeder Config but it is still using the default options when constructing the DatabaseConnector.

Is there any workaround for this in the current version?
Thanks!

**Comment by pkosiec** [comment]
Hi @lukasburns,
Thanks for reporting the issue. Indeed, there are two bugs. Sorry for that! 
- MongoClient should be passed to DB connector
- default `connectTimeoutMS` value should be equal to `databaseReconnectTimeout` from SeederConfig

I fixed them in https://github.com/pkosiec/mongo-seeding/pull/110/files and I will release a bugfix soon.

Cheers!

**Comment by lukasburns** [comment]
Awesome!
Thank you very much!

**Comment by pkosiec** [comment]
@lukasburns No problem :) Let me know if the 3.4.1 works fine for you!

**Comment by lukasburns** [comment]
Works Beautifully, thanks again!

**Comment by pkosiec** [comment]
Wonderful :) Thanks for verifying the bugfix and enjoy using Mongo Seeding 🙂
