### ISSUE TITLE
Timestamps feature + tsconfig question

### ISSUE THREAD

**Issue by benjaminb-** [pkosiec/mongo-seeding#122]
Hi!

At first a big thank you for your work on this package, we are using it since a few month at work, and we love the way we can use typescript and not only json to seed our databases.

It could be great to have these features :
* add a transformer to set timestamps (createdAt, updatedAt)
* add CLI option to set the timestamps (based on the previous transformer)

I can work on this PR if you are OK with that ?

Also, maybe I missed something, but I would like to use my typescripts models inside data typescript files.

I did it and it's working well except when some models are using imports with paths, is there a way to specificy which tsconfig file to use when use CLI ?
Thanks

**Comment by pkosiec** [comment]
Hi @benjaminb-,
Thanks for very kind words! I'm glad you like the project 🙂 

Yes, I would definitely accept PR with the timestamp transformer and also CLI + Docker image options (env variables/command line arguments). They could be named `--set-timestamp` and `SET_TIMESTAMP` - but if you have better idea, go for it. Thanks!

> Also, maybe I missed something, but I would like to use my typescripts models inside data typescript files.

You should be able to do it. Please see the example: https://github.com/pkosiec/mongo-seeding/tree/master/examples/import-data-ts

If you will still have problem, please create another issue with some snippets, I will try to do my best to help you.

Cheers!

**Comment by pkosiec** [comment]
Oops, I missed one of your questions:
> is there a way to specificy which tsconfig file to use when use CLI 

Nope, not at the moment. CLI and Docker image use `ts-node`, which loads tsconfig.json automatically: https://github.com/TypeStrong/ts-node#loading-tsconfigjson

However, it should be easily done via `--project` option: https://github.com/TypeStrong/ts-node#cli-and-programmatic-options
Please create another issue with some basic example what do you want to achieve, and I will try to implement this 🙂

**Comment by benjaminb-** [comment]
Cool i'm gonna work on the PR this week!
Thanks for the Typescript precisions, i'm gonna try again :)
