### ISSUE TITLE
Wrong export in Custom Docker Image sample data helpers

### ISSUE THREAD

**Issue by jjpatel361** [pkosiec/mongo-seeding#123]
Hi 👋  

@pkosiec  Fantastic project! and a great design. I was working with this file when I found an unqualified export.  I see `getObjectId` is imported and re-exported but not `getObjectIds` 

https://github.com/pkosiec/mongo-seeding/blob/3ea7eb252024a71bb02eed671e5ab32c89004179/examples/custom-docker-image/sample-data/helpers/index.js#L17

It is a super easy fix or even no fix at all. 

Again. Kudos to you on this one. 👏

**Comment by pkosiec** [comment]
Hi @jjpatel361,
Thanks for very kind words 🙂 Glad you like this project.

You're right, this line shouldn't be here. Good catch! If you would like to, then you can open a PR with removal of this line 🙂 If you don't want to, then no problem, I will prepare a PR in the following day or so. 

Cheers!
