### ISSUE TITLE
Drop Collection option?

### ISSUE THREAD

**Issue by mrdanielm** [pkosiec/mongo-seeding#13]
Is there a way to drop the collections to be seeded before a new set of seed data goes in? Dropping the entire database isn't always the desired option so a compromise in the middle would be nice

**Comment by pkosiec** [comment]
Hi,
Currently there is no option to do so. But I think this is a very good idea. I will try to prepare it in the following days.

**Comment by mrdanielm** [comment]
Perfect sounds great! Yeah I think both options have there use cases depending on the structure of the database.

**Comment by pkosiec** [comment]
@mrdanielm Good news! The brand new version of Mongo Seeding has been just published. It brings the feature requested by you - check it out! https://github.com/pkosiec/mongo-seeding/releases/tag/v2.2.0
