### ISSUE TITLE
Exit code 0 on fail

### ISSUE THREAD

**Issue by schw4rzlicht** [pkosiec/mongo-seeding#145]
Hey there,

I noticed that if there are typescript compilation errors during seed when running the CLI, it exits with exit code 0. That's kind of unfortunate since we are using the CLI tool in our CI pipelines for a nightly reset of the developer databases. If the seed fails, the pipeline still succeeds.

I took a first glimpse and I would blame this part: https://github.com/pkosiec/mongo-seeding/blob/35c31a2b8d2d0719a8fc1c3f2aaec71a586547ad/cli/src/index.ts#L56-L59

Is there a reason you do `process.exit(0)`? Otherwise I'd create a PR to fix it.

**Comment by pkosiec** [comment]
Hi @schw4rzlicht,
You're absolutely right. CLI should exit with error in this case.

This is embarrassing, but the error behavior was there for more than 2 years now. 😅 Not sure what was the initial reason to go with this totally wrong approach. Anyway, sorry for troubles. You don't need to open the PR - fix is incoming!
