### ISSUE TITLE
Remove all documents?

### ISSUE THREAD

**Issue by EltonGarcia** [pkosiec/mongo-seeding#148]
Is there any option to remove all documents before seeding the database/collection without dropping them?
I can see that there are options to drop the database/collection, however, dropping the collection means also delete the indexes, which in most cases will be undesirable.

**Comment by pkosiec** [comment]
Hi @EltonGarcia,

As you noticed this feature is not yet available. Thank you for your contribution, I'll try to review your PR in the following days. Once your PR is merged, I will publish an alpha release. Cheers!

**Comment by pkosiec** [comment]
Hello again @EltonGarcia, I've just published new draft release: https://github.com/pkosiec/mongo-seeding/releases/tag/v3.7.0-alpha.0. Thanks again for your solid pull request 🙂
