### ISSUE TITLE
code runs but does not seed DB

### ISSUE THREAD

**Issue by listguy** [pkosiec/mongo-seeding#152]
Does this library still maintained?

**Comment by pkosiec** [comment]
Yes it is, you can see new commits and releases on the repo. Do you have any issue? If so, please describe it throughtly.

**Comment by listguy** [comment]
Hey, yes I do have an issue. Just wanted to make sure I'm not putting effort describing the issue for nothing 😅
Anyway I was  earlier trying to seed my DB (I am working on [mongoDB atlas](https://www.mongodb.com/cloud/atlas)) with a pre made JSON file. I followed the instructions in [importing-data](https://github.com/pkosiec/mongo-seeding/tree/master/examples/import-data) and [imported data definition](https://github.com/pkosiec/mongo-seeding/blob/master/docs/import-data-definition.md) and this is what I came up with: 

`seeder.js`
```js
require("dotenv").config();
const { Seeder } = require("mongo-seeding");
const path = require("path");

const config = {
  database: process.env.MONGO_URI,
  dropDatabase: false,
};

const seeder = new Seeder(config);

const seed = seeder.readCollectionsFromPath(path.resolve("./seeds/tickets"), {
  transformers: [Seeder.Transformers.replaceDocumentIdWithUnderscoreId],
});

seeder
  .import(seed)
  .then((_) => console.log("seeded successfully"))
  .catch((err) => {
    console.log(err);
    console.log("error");
  });

```

`tickets.json`:
```
  [{
    // Array of dummy data objects
  }]
```

File structure is like so:
```
     .
   ├── server
   │    ├── seeds
   │    │   └── tickets
   │    │      └── tickets.json
   │    └── seeder.js
```

When I tried to run `seeder.js` the code executes and a "seeded successfully" message logged to the console.
However, the collection was still empty. I tried to debug and found out `seed` was just an empty array `[]`. 
Seems like there is a problem in `seeder.readCollectionsFromPath()`? (No error message was logged to the console)

PS. in the end I managed to dig into the `node_modules`  and follow the errors in the console, and came up with a workaround solution like so:

`seeder.js`:
```js
require("dotenv").config();
const { Seeder } = require("mongo-seeding");
const fs = require("fs");
const config = {
  database: process.env.MONGO_URI,
  dropDatabase: false,
};

const seeder = new Seeder(config);

// const seed = seeder.readCollectionsFromPath(path.resolve("./seeds/tickets"), {
//   transformers: [Seeder.Transformers.replaceDocumentIdWithUnderscoreId],
// });

const seed = fs.readFileSync("./tickets.json");

seeder
  .import([JSON.parse(seed)])
  .then((_) => console.log("seeded successfully!"))
  .catch((err) => {
    console.log(err);
    console.log("error");
  });

```

`tickets.json`:
```
   {
      "name": "tickets",
      "documents": [
        // mock data ...
      ]
    } 
```

**Comment by pkosiec** [comment]
From what I can see you have totally different content from what is described in the documentation [here](https://github.com/pkosiec/mongo-seeding/blob/master/docs/import-data-definition.md).

You wrote:
```javascript
seeder.readCollectionsFromPath(path.resolve("./seeds/tickets"), ...)
```

But in fact you should point to `./seeds`:
```javascript
seeder.readCollectionsFromPath(path.resolve("./seeds"), ...)
```

Collections are represented by directories. Also, the `tickets.json` has invalid content. See the document I linked above to fix it.

Closing it for now as it works as described in docs. If it won't work, please write a comment here and I can reopen it 🙂 However, please double check you followed the official guides first. Cheers!
