### ISSUE TITLE
Provide docker image based on regular node image

### ISSUE THREAD

**Issue by softwarexpert24** [pkosiec/mongo-seeding#180]
# Provide docker image based on regular node image

I currently have the need to build a customized docker image on top of the mongo-seeding one containing additional tools, such as the netcat-openbsd and mongodb-org-shell packages. Especially the latter one is not available for the Alpine linux distribution. Thus, it would be very helpful if an additional docker image could be provided using the regular node image as basis which is itself based on the regular Debian linux distribution.

Shortly, I'm going to provide a PR which provides a parallel dev.Dockerfile file used for building that additional docker image based on Debian.

**Comment by softwarexpert24** [comment]
Actually, I just noticed that I can solve the issue differently by building a custom docker image directly on top of the mongo-seeding CLI consumed from npm. Sorry for the confusion.

**Comment by pkosiec** [comment]
Hi @softwarexpert24, thanks for your contribution. Yes, currently building the image by yourself is the best way to do it. 

However, I'm not against building more Mongo Seeding Docker images using different base images. It all depends on the demand from the community. So if there are other people interested in such feaure, please post a comment here and I can revisit this topic, reopen issue and PR. Thanks!

**Comment by softwarexpert24** [comment]
> Hi @softwarexpert24, thanks for your contribution. Yes, currently building the image by yourself is the best way to do it.
> 
> However, I'm not against building more Mongo Seeding Docker images using different base images. It all depends on the demand from the community. So if there are other people interested in such feaure, please post a comment here and I can revisit this topic, reopen issue and PR. Thanks!

Well, I would definitely be interested. I'm using Mongo Seeding with a customized docker image now and need to install some additional tools within that docker image, such as Mongo Shell and netcat-bsd.
