### ISSUE TITLE
Can i use async functions within the helpers?

### ISSUE THREAD

**Issue by kratoskat** [pkosiec/mongo-seeding#199]
Trying to do some api calls in one of the helper functions before the data is imported but it doesnt seem to work. 

Can you confirm whether i am able to run async functions within the helpers?

**Comment by pkosiec** [comment]
Hi @kratoskat,
What do you mean by helpers? 
Do you mean transformers? If so, then unfortunately not: https://github.com/pkosiec/mongo-seeding/blob/main/core/src/transformer/transformer.ts#L20-L22. But you can easily iterate over collections and do your own stuff before calling `import`.

Hope that helps!

**Comment by kratoskat** [comment]
it does, thanks :)
