### ISSUE TITLE
wrapError: Cannot set property name

### ISSUE THREAD

**Issue by qqilihq** [pkosiec/mongo-seeding#211]
I'm just trying out mongo-seeding 3.8.0-alpha.0 - happy to see the progress here!

I had an issue in my existing code which would trigger a `BSONVersionError` (from the `bson` module). The `wrapError` in this lib tries to change the name of the caught error which fails in case of `BSONVersionError` as it is a readonly property.

The exception said `TypeError: Cannot set property name of  which has only a getter` which caused me quite some confusion, head banging, and a while to figure out.

Suggestion - replace the wrap error logic with something like this:

```ts
const wrapError = (err: Error) => {
  return new Error('MongoSeedingError', { cause: err });
};
```

**Comment by pkosiec** [comment]
Hi @qqilihq,
Thank you for your patience. Yes, I think your idea seems to be the best option. As I didn't want to require Node 16.9+ with `error.cause` support, I included a pollyfill which should do. the trick. What do you think about this PR? https://github.com/pkosiec/mongo-seeding/pull/213

**Comment by qqilihq** [comment]
Hi @pkosiec  - sounds good to me, thank you very much! 👍

**Comment by pkosiec** [comment]
Good news @qqilihq! 4.0.0 alpha is now ready to test: https://github.com/pkosiec/mongo-seeding/releases/tag/v4.0.0-alpha.0

Please let me know if it fixes your issue!

**Comment by qqilihq** [comment]
@pkosiec Great, thank you! I'll give it a try and will gladly provide feedback if needed :-)
