### ISSUE TITLE
How do we insert documents/fields with an index?

### ISSUE THREAD

**Issue by AndreasGalster2** [pkosiec/mongo-seeding#212]
Given a schema such as this:

```
const mongoose = require('mongoose');

const locationDetailSchema = new mongoose.Schema({
  referrer_id: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
  },
  locationType: {
    type: String,
    enum: ['USER', 'VENDOR', 'DELIVERY_ADDRESS'], // Point for GPS coordinates
    required: true,
  },
  gpsInfo: {
    type: {
      type: String,
      enum: ['Point'],
      required: true,
    },
    coordinates: {
      type: [Number],
      required: true,
    },
  },
  locationName: String,
  locationAddress: String,
  locationGooglePlacesJSON: String, // This is a JSON String from Google Places API
});

locationDetailSchema.index({ gpsInfo: '2dsphere' });

module.exports = mongoose.models.LocationDetail || mongoose.model('LocationDetail', locationDetailSchema);

```

You can see there is a special index with type 2dsphere on the gpsInfo field which allows for geoSpatial queries to be defined... 

```
      let sortedLocations;
      try {
        sortedLocations = await LocationDetail.find({
          gpsInfo: {
            $nearSphere: {
              $geometry: {
                type: 'Point',
                coordinates: [userLocation[1], userLocation[0]],
              },
              $maxDistance: 900 * 1000, // kilometers multiplier
            },
          },
        })
          .limit(limit)
          .exec();
```

I noticed my integration test wasn't returning any results, so I disabled the GPS query in my find operation and it returned results. I am pretty sure it is not returning anything because there is no index/info for the gpsInfo field being inserted when I seed the data.

```
const vendorLocations = [
  {
    _id: getObjectId('locationTest_Location1'),
    locationType: 'VENDOR',
    gpsInfo: {
      type: 'Point',
      coordinates: [123.885437, 10.315699],
    },
    locationName: 'Cebu Address Name',
    locationAddress: 'Some Address Details',
    locationGooglePlacesJSON: someJsonHere,
    referrer_id: getObjectId('locationTest_Vendor1'),
  },
];

module.exports = vendorLocations;
```

**Comment by pkosiec** [comment]
Hey @AndreasGalster2,
If I understood correctly, it seems that this is an issue related to Mongoose's index creation instead of the Mongo Seeding itself 🤔 What Mongo Seeding does is creating collections and inserting multiple documents into them (see the code here: https://github.com/pkosiec/mongo-seeding/blob/49ebbaf40bca10935b52941cae22e8a11595626f/core/src/database/database.ts#L56). If you see any possible improvements around that, please let me know.

Cheers!

**Comment by pkosiec** [comment]
Hey, it's been a while already. I'm closing the issue. Feel free to comment it / create another one if you need more help related to Mongo Seeding. Cheers!
