### ISSUE TITLE
Incorrect links in NPM readmes

### ISSUE THREAD

**Issue by sebilasse** [pkosiec/mongo-seeding#51]
About the [npm readme](https://www.npmjs.com/package/mongo-seeding) :
<img width="621" alt="bildschirmfoto 2018-10-11 um 14 36 33" src="https://user-images.githubusercontent.com/750300/46804540-291ca680-cd63-11e8-865a-75f1cb9fb311.png">

The link to the tutorial is wrong 
`https://github.com/pkosiec/mongo-seeding/blob/docs/import-data-definition.md` `-> 404`
correct link:
`https://github.com/pkosiec/mongo-seeding/blob/master/docs/import-data-definition.md`

**Comment by pkosiec** [comment]
Hi @sebilasse,
Thank you for reporting this! It is because I used relative links. I will change them to absolute ones. The change will be live in final 3.0.0 release, which is just behind the corner. 🙂
