### ISSUE TITLE
Update DB URI Parsing from CLI Params to Allow mongoDB+srv protocol

### ISSUE THREAD

**Issue by BenedictRasmussen** [pkosiec/mongo-seeding#63]
I am deploying a Mongo instance using Mongo Atlas. In one of the newer driver versions, a new protocol was added to allow connecting to a Mongo cluster without having to specify all hosts in the cluster. Details may be found in the [MongoDB 3.6 docs](https://www.mongodb.com/blog/post/mongodb-3-6-here-to-SRV-you-with-easier-replica-set-connections). The `mongo-seeding-cli` works fine with the new protocol if the user specifies the connection address using a DB URI string. However, the user is unable to specify individual parameters using the new service because the [core mongo seeding library](https://github.com/pkosiec/mongo-seeding/blob/master/core/src/database/database-connector.ts) automatically adds a port to the connection string, which is not allowed when connecting to mongo using the `mongo+srv` protocol.

```
mongo-seeding Connecting to mongodb+srv://<myAdmin>:<myPassword>@runewordfinder-0ltsc.mongodb.net:27017/runewordfinder... +9ms
(node:73572) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
  mongo-seeding Ports not accepted with `mongodb+srv` URIs
```

I would like to be able to specify the individual parameters so I may hide my password as an environment variable. I propose that `core/src/database/database-connector.ts#getDbConnectionUri(...)` is updated to check the provided protocol and create an appropriate string that:
- Includes the port if `protocol === 'mongodb'`
- Does not include the port if `protocol === 'mongodb+srv'`

**Comment by pkosiec** [comment]
I have just one comment to your PR - please make a small suggested change and I will merge it shortly.

**Comment by BenedictRasmussen** [comment]
Do you plan on publishing a new version to NPM soon, by chance?

**Comment by pkosiec** [comment]
@BenedictRasmussen Sure thing - I'm going to update dependencies and then I will publish new release 🙂It should arrive in next 2 hours.

**Comment by pkosiec** [comment]
@BenedictRasmussen here it is! 
https://github.com/pkosiec/mongo-seeding/releases/tag/v3.1.1 🚀
