### ISSUE TITLE
Support Extended JSON format

### ISSUE THREAD

**Issue by rickitan** [pkosiec/mongo-seeding#69]
Hi @pkosiec,

Awesome job at the library, it's very useful.

I'm running into an issue. I'm inserting data from a JSON file. In the file I have an "_id" field which should be MongoDB ObjectId.

The issue is that it gets inserted as plain text.

This syntax should lead to the creation of ObjectIds: 

```
{ 
 "_id" : {"$oid":"5a68fdc3615eda645bc6bdec"}
}
```

But it throws an error locally: `{ MongoSeedingError: Error: key $oid must not start with '$'`

I found that syntax here: https://stackoverflow.com/questions/51439955/mongoimport-id-is-not-an-objectid

Is there a way to end up with ObjectIds instead of plain text ids?

Thank you

**Comment by pkosiec** [comment]
Hello @rickitan,

Thank you for kind words. 

At the moment Mongo Seeding loads JSON files as JavaScript objects without support for the MongoDB Extended JSON: https://docs.mongodb.com/manual/reference/mongodb-extended-json/#mongodb-extended-json

However, that would be a great feature. It would make users able to import files exported with `mongoexport`. I will take a look at existing libraries for reading this format and maybe I will be able to implement that quickly.

For now I would suggest the workaround: https://stackoverflow.com/questions/51439955/mongoimport-id-is-not-an-objectid#comment89927940_51440423 
(of course you can do it also from your Node.js app).

**Comment by pkosiec** [comment]
Hello again @rickitan,
Good news! I implemented the feature and merged it to master. You can test a new prerelease with Extended JSON syntax support 🚀 

https://github.com/pkosiec/mongo-seeding/releases/tag/v3.2.0-alpha.0

**Comment by pkosiec** [comment]
@rickitan Please test the 3.2.0-alpha.0 version and let me know, if it is OK. If so, I will release the final 3.2.0 🙂

**Comment by rickitan** [comment]
Hi @pkosiec,

I just tried it. It works like a charm 🎊

Amazing job. That was really fast!!!

Thank you very much.

**Comment by pkosiec** [comment]
@rickitan Awesome, thanks for testing! So today I will release the final 3.2.0 version.

**Comment by mtapdilli** [comment]
Hi @rickitan @pkosiec ,
does this work only for "$oid" ? or will this also works for ints, longs and other strings of extended json ? i have just tried seeding a file I have exported from mongodb with extended json format that has something like this.

`"lastModified": { "$numberLong": "1601911555917" },`

and after seeding this, in the database I see that it is written something like 1601911555917**.0** against the field lastModified. I think the expected should be NumberLong('1601911555917'). Can you please confirm if this supports other e-JSON strings as well ?

**Comment by pkosiec** [comment]
Hi @mtapdilli,
I'm using EJSON parser from official MongoDB `bson` package. What I do is 
```javascript
return EJSON.parse(content, {
   relaxed: true,
});
```
https://github.com/pkosiec/mongo-seeding/blob/master/core/src/populator/filesystem.ts#L125

However, maybe the relaxed mode messes things up?

> **Relaxed Mode**
>    A string format that emphasizes readability and interoperability at the expense of type preservation. That is, conversion from relaxed format to BSON can lose type information.

Could you please try using `canonical` mode e.g. with modified mongo-seeding that uses this mode while parsing EJSON? If that will be the case, I can add additional parameters to configure EJSON parsing mode.

Cheers!

**Comment by mtapdilli** [comment]
Thanks for the suggestion @pkosiec . Changing **relaxed to false** worked fine . I am not an expert, so would request you to double check and make the change accordingly. Cheer!

**Comment by Fiyin-Anne** [comment]
Hi @mtapdilli @pkosiec  I am currently getting the error message `MongoSeedingError: Error: key $oid must not start with '$'`. In what file do I change **relaxed to false**?

If it helps:
- mongo-seeding: "^3.4.1",
- mongodb: "^3.6.2",
- mongoose: "^5.10.10",

**Comment by pkosiec** [comment]
Hi @Fiyin-Anne,
Because EJSON parsing is enabled by default for all JSON files, it should work normally. Just to double check: do you have something like this in your `json` file?
```
{ 
 "_id" : {"$oid":"5a68fdc3615eda645bc6bdec"}
}
```
If so, it should work.


The error you provided shouldn't be related to the EJSON parsing mode. Anyway, currently there is no support for changing mode of EJSON parsing, however I will introduce it very shortly.

**Comment by Fiyin-Anne** [comment]
Yeah, I did but it was in a `js` file 🤦🏾‍♀️ I have corrected it now and I am no longer getting the error, Thanks!

**Comment by pkosiec** [comment]
Glad it worked 👍 Cheers!

**Comment by pkosiec** [comment]
Good news @mtapdilli, new alpha release supports EJSON mode configuration: https://github.com/pkosiec/mongo-seeding/releases/tag/v3.6.0-alpha.0 - check it out! 🙂

**Comment by Turkzilla** [comment]
I am having this exact issue:

Data file has referenced id field:
`company: { "$oid": "23456784eca96f93827164a4" },`

But every file with _id: or ref: returning this error:
```
Error [MongoSeedingError]: MongoSeedingError: key $oid must not start with '$'
    at serializeInto
```
