### ISSUE TITLE
Leaking credentials in logs

### ISSUE THREAD

**Issue by hongkongkiwi** [pkosiec/mongo-seeding#72]
Just noticed that in the docker logs it will show this:
```
mongo_seed_1  | 2019-06-18T03:48:24.527Z mongo-seeding Connecting to mongodb://user:pass@mongodb:27017/db...
```

I'm using the dockerfile, I recommend to add a env as follows `HIDE_CREDS=true`

If set, I think it would make sense to have an environment variable to mask the user:pass like this:
mongodb://HIDDEN_USER:HIDDEN_PASS@mongodb:27017/db...

That way, anybody viewing the logs doesn't automatically have  access to the user/pass.

**Comment by pkosiec** [comment]
Hi @hongkongkiwi,
Thank you for reporting the issue. I agree, this is a must have. 

Instead of creating new environmental variable, I will always mask user:pass.

**Comment by hongkongkiwi** [comment]
Perfect!

**Comment by pkosiec** [comment]
@hongkongkiwi The bug has been fixed! The new version of Mongo Seeding will come soon.

**Comment by hongkongkiwi** [comment]
Super awesome thanks!
