### ISSUE TITLE
Silence logger

### ISSUE THREAD

**Issue by soanvig** [pkosiec/mongo-seeding#84]
Hello!

We are using this library in company, mostly for seeding database before each test. It works great, but the logging is terrible feature for us. It may be useful for one-time seeding, but since every our test generates such logs, our log from testing is bloated.

Could you please either implement logging silence, or point out how it should be properly done, so I can prepare PR? I looked into the code and I have at least few ideas how to configure logger (since it's just a sample function now), so we could discuss that perhaps

**Comment by pkosiec** [comment]
Hello @soanvig, which Mongo Seeding type do you use? 

In case of Core (TS library):
The logging should be disabled by default. You can see how to configure it here: https://github.com/pkosiec/mongo-seeding/tree/master/core#debug-output

In case of CLI, I can see that indeed there is no option to do so. I will implement `--silent` flag soon. Stay tuned!

**Comment by pkosiec** [comment]
BTW, in the meantime, you can pipe the logs to `/dev/null`. Like:
```bash
seed ./ > /dev/null
```

**Comment by soanvig** [comment]
Thank you, we use library, but still get logs.

Gonna see tomorrow what sits there precisely, maybe something is poorly configured on our side.

**Comment by pkosiec** [comment]
@soanvig Okay, I've just checked an example from this repository and without setting `DEBUG` env there is no logs in stdout, apart from `DeprecationWarning` related to MongoDB update. However, this is still an issue for CLI, so thanks for good suggestion.
