### ISSUE TITLE
Error with custom import order

### ISSUE THREAD

**Issue by KROSF** [pkosiec/mongo-seeding#94]
The import order is not correct when you start in zero and eventually you reach 10,
the 10 becomes the second following lexicographic string order.
For now, I decided to start counting from 100.

**Comment by pkosiec** [comment]
Hi @KROSF, thank you for reporting the issue. I will try to reproduce it and prepare a fix.

**Comment by pkosiec** [comment]
Hi again, @KROSF, check out the latest prelease - the issue should be resolved now. Let me know if it works 🙂 
https://github.com/pkosiec/mongo-seeding/releases/tag/v3.4.0-alpha.1
