### ISSUE TITLE
Provide a way to pass insertMany options 

### ISSUE THREAD

**Issue by BryceDoganer** [pkosiec/mongo-seeding#99]
We have run into situations where we are seeding a collection that we would prefer not to drop, but it's not possible to seed data through `mongo-seeding` because of a duplicate key that already exists in said collection.

It would be beneficial to be able to pass the option to submit an "unordered" list of documents so that if a duplicate key error occurs, the rest of the documents will still be written, instead of the seeder stopping altogether.   

Here is the documentation for the `insertMany` method which allows an `options` object to be passed in: 
https://mongodb.github.io/node-mongodb-native/3.3/api/Collection.html#insertMany

This is where the `options` could be passed in: 
https://github.com/pkosiec/mongo-seeding/blob/3e983e09948b5c4109166fa935902dfdcb8be2db/core/src/database/database.ts#L25

Example if we are able to pass an `insertManyOptions` Object: 
`return this.db.collection(collectionName).insertMany(documentsCopy, insertManyOptions);`

**Comment by pkosiec** [comment]
Hi @BryceDoganer, thanks for your feedback. I agree, the options should be passed easily. I will update the implemention soon for final 3.4.0. Cheers!
